hongmumuk/hongmumuk_iOS

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Dependency/ValidationClient.swift, hongmumuk_SwiftUI/Enums/Univ.swift, hongmumuk_SwiftUI/Extension/Univ+.swift
- Validation을 담당할 객체인 `validationClient를` 추가했습니다.
- 확장성을 고려해서, 대학 타입인 `Univ`를 만들었습니다.
- Univ를 확장해 대학별 email, password 정규식을 `validationClient`에서 주입받도록 처리했습니다.
- 마지막 커밋은 테스트용으로 남겨뒀고, 리뷰 완료 시 삭제할 예정입니다.
- 따라서, 테스트를 위해서는 마지막 커밋으로 빌드하시면 됩니다.
- 리뷰는 마지막 커밋 이전의 내용만 하시면 됩니다.
</p>
=> [Feat] validationClient 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj
- network 작업을 위한 alamofire 패키지 설치
=> [Chore] alamofire 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Feature/Auth/LoginFeature.swift
[###](url) PR 작성전 체크 목록
- [화면 링크](https://www.figma.com/design/7s3DRvmyDjXSvHr9szPdDu/🍙-홍무묵_UI?node-id=296-33255&t=uqwvZ9mG9j8L3Rk4-0)
- 해당 화면의 action, state, reducer를 정의했습니다.
=> [Feat] login store 추가

hongmumuk_SwiftUI/DesignSystem/Colors.swift
Issue Number: 
- 디자인 시스템 중 컬러들의 색상을 업데이트 하였습니다
=> [style] 디자인 시스템 업데이트 

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Extension/Double+.swift, hongmumuk_SwiftUI/Feature/Home/HomeCircleView.swift, hongmumuk_SwiftUI/Feature/Home/HomeFeature.swift, hongmumuk_SwiftUI/Feature/Home/HomeHeaderView.swift, hongmumuk_SwiftUI/Feature/Home/HomeRandomButton.swift, hongmumuk_SwiftUI/Feature/Home/HomeView.swift
- 홈 view 및 store를 추가했습니다.
- [문서](https://www.notion.so/akaseoyoung/198630c6c92f8078b771e04cdc1f7a61#19c630c6c92f808594eff9665358e7f7) 참고 바랍니다.
- 문서에 기재
=> [refactor] home store/ view 추가

hongmumuk_SwiftUI/Dependency/Client/RestaurantClient.swift, hongmumuk_SwiftUI/Dependency/Client/UserDefaultsClient.swift, hongmumuk_SwiftUI/Dependency/Error/RestaurantListError.swift, hongmumuk_SwiftUI/Dependency/Model/RestaurantListModel.swift, hongmumuk_SwiftUI/Dependency/Model/RestaurantListRequestModel.swift, hongmumuk_SwiftUI/Enums/Cateogory.swift, hongmumuk_SwiftUI/Enums/Sort.swift
- 최근 검색어 저장을 위한 UserDefaultsClient추가 
- 식당 리스트를 위한 RestrauntClient 추가
=> [feat] 서치 기능에 필요한 Dependency 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Dependency/Client/RestaurantClient.swift, hongmumuk_SwiftUI/Dependency/Model/RestaurantListModel.swift, hongmumuk_SwiftUI/Extension/String+.swift, hongmumuk_SwiftUI/Feature/Search/SearchFeature.swift
- 서치 store 추가
- [문서](https://www.notion.so/akaseoyoung/19b630c6c92f803dbfa2ed733693d86b)에 상세 내용 첨부
=> [feat] 서치 store 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Assets.xcassets/xIcon.imageset/Contents.json, hongmumuk_SwiftUI/Assets.xcassets/xIcon.imageset/xIcon.svg, hongmumuk_SwiftUI/Extension/View+.swift, hongmumuk_SwiftUI/Feature/Home/HomeView.swift, hongmumuk_SwiftUI/Feature/Search/SearchHeaderView.swift, hongmumuk_SwiftUI/Feature/Search/SearchListView.swift, hongmumuk_SwiftUI/Feature/Search/SearchRecentView.swift, hongmumuk_SwiftUI/Feature/Search/SearchView.swift
- 서치 화면 UI 제작
- 검색 결과가 없는 경우는 아직 처리하지 않음(추후 UI 완성되면 처리 예정)
</p>
=> [Feat] 서치 UI 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Assets.xcassets/dropdownIcon.imageset/Contents.json, hongmumuk_SwiftUI/Assets.xcassets/dropdownIcon.imageset/dropdownIcon.svg, hongmumuk_SwiftUI/Feature/List/ListFeature.swift, hongmumuk_SwiftUI/Feature/List/ListFilterView.swift, hongmumuk_SwiftUI/Feature/List/ListHeaderView.swift, hongmumuk_SwiftUI/Feature/List/ListItemView.swift, hongmumuk_SwiftUI/Feature/List/ListRandomButton.swift, hongmumuk_SwiftUI/Feature/List/ListView.swift, hongmumuk_SwiftUI/Feature/List/ListViw.swift, hongmumuk_SwiftUI/Feature/Reusable/InquiryButton.swift
- list 피쳐 구현 시 필요한 파일을 추가했습니다.
=> [chore] list feature에 들어갈 리소스 추가

hongmumuk_SwiftUI/Dependency/Model/RestaurantListModel.swift, hongmumuk_SwiftUI/DesignSystem/Fonts.swift, hongmumuk_SwiftUI/Enums/Sort.swift, hongmumuk_SwiftUI/Feature/List/ListFeature.swift, hongmumuk_SwiftUI/Feature/Search/SearchListView.swift
- RestaurantListModel 일부 수정
- list store 설계 및 추가
- [문서](https://www.notion.so/akaseoyoung/1a5630c6c92f802d8c6ad93ad025ce3c)
=> [feat] 카테고리 리스트 store 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Dependency/Client/LikeClient.swift, hongmumuk_SwiftUI/Feature/Like/LikeEmptyView.swift, hongmumuk_SwiftUI/Feature/Like/LikeFeature.swift, hongmumuk_SwiftUI/Feature/Like/LikeFilterView.swift, hongmumuk_SwiftUI/Feature/Like/LikeHeaderView.swift, hongmumuk_SwiftUI/Feature/Like/LikeListView.swift
=> [Chore] 찜 기능에 필요한 리소스 추가

hongmumuk_SwiftUI/DesignSystem/Colors.swift, hongmumuk_SwiftUI/DesignSystem/DesignSystem.swift, hongmumuk_SwiftUI/DesignSystem/Effects.swift, hongmumuk_SwiftUI/Extension/Text+.swift, hongmumuk_SwiftUI/Feature/Home/HomeView.swift
=> [Chore] 린팅된 디자인 시스템 코드 추가

hongmumuk_SwiftUI/Feature/Like/LikeEmptyView.swift, hongmumuk_SwiftUI/Feature/Like/LikeFilterView.swift, hongmumuk_SwiftUI/Feature/Like/LikeHeaderView.swift, hongmumuk_SwiftUI/Feature/Like/LikeListView.swift, hongmumuk_SwiftUI/Feature/Like/LikeView.swift, hongmumuk_SwiftUI/hongmumuk_SwiftUIApp.swift
=> [feat] Like UI 추가

hongmumuk_SwiftUI/Dependency/Client/KeywordClient.swift, hongmumuk_SwiftUI/Dependency/Client/RestaurantClient.swift, hongmumuk_SwiftUI/Dependency/Error/RestaurantDetailError.swift, hongmumuk_SwiftUI/Dependency/Model/Blog.swift, hongmumuk_SwiftUI/Dependency/Model/RestaurantDetail.swift, hongmumuk_SwiftUI/Enums/Keyword.swift
- 식당 단일 조회를 위한 getRestaurantDetail 메서드를 기존 RestaurantClient에 추가했습니다.
- 블로그 제목과 내용에서 keyword를 추출하기 위해서 keywordClient를 추가했습니다.
=> [Feat] detail dependency 추가

hongmumuk_SwiftUI/Extension/String+.swift, hongmumuk_SwiftUI/Feature/Detail/DetailFeature.swift
- detail 기능에 필요한 store 추가했습니다.
- [문서](https://www.notion.so/akaseoyoung/1a6630c6c92f8090a42de0ccd98919fe) 참고해주세요.
=> [Feat] detail store 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Feature/Category/CategoryView.swift, hongmumuk_SwiftUI/Feature/Detail/DetailInfoView.swift, hongmumuk_SwiftUI/Feature/Detail/DetailMapView.swift, hongmumuk_SwiftUI/Feature/Detail/DetailReviewView.swift, hongmumuk_SwiftUI/Feature/Detail/DetailTabButtonView.swift, hongmumuk_SwiftUI/Feature/Detail/DetailTabView.swift, hongmumuk_SwiftUI/Feature/Detail/DetailView.swift, hongmumuk_SwiftUI/Feature/Like/LikeView.swift, hongmumuk_SwiftUI/Feature/Search/SearchView.swift
=> [Feat]detail UI 추가

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Feature/Random/RandomFeature.swift, hongmumuk_SwiftUI/Feature/Random/RandomView.swift
- 랜덤 기능에 필요한 resource를 추가했습니다.
=> [chore] random resource 추가

hongmumuk_SwiftUI/Feature/Random/RandomFeature.swift
- [문서](https://www.notion.so/akaseoyoung/1a6630c6c92f809896e7ccb99ae5d2ff) 참고해주세요.
=> [Feat] random store 추가

hongmumuk_SwiftUI/Feature/Category/CategoryView.swift, hongmumuk_SwiftUI/Feature/Home/HomeView.swift, hongmumuk_SwiftUI/Feature/Random/RandomView.swift
=> [Feat] random UI 추가

hongmumuk_SwiftUI/Feature/Auth/ResetPasswordFeature.swift, hongmumuk_SwiftUI/Feature/Auth/VerifyEmailFeature.swift
Issue Number: 
- Verify Email Feature 추가
- Reset Password Feature 추가
=> [Feat] FindPassword Store 추가

hongmumuk_SwiftUI/Feature/Auth/VerifyEmailFeature.swift
Issue Number: 
- Email이 API 통신에 사용되기 때문에 유저디폴트 추가
=> [Fix] VeifyEmail 유저디폴트 사용으로 변경

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Feature/Auth/PrivacyModalView.swift, hongmumuk_SwiftUI/Feature/Auth/PrivacyView.swift, hongmumuk_SwiftUI/Feature/Auth/SignupDoneView.swift, hongmumuk_SwiftUI/Feature/Auth/SignupEmailView.swift, hongmumuk_SwiftUI/Feature/Auth/SignupPasswordView.swift, hongmumuk_SwiftUI/Feature/Auth/SignupToastView.swift, hongmumuk_SwiftUI/Feature/Reusable/CommonTextFieldView.swift, hongmumuk_SwiftUI/Feature/Reusable/SignupHeaderView.swift
Issue Number: 
- Signup View 추가
=> [Feat] Signup View 추가

hongmumuk_SwiftUI/Feature/Auth/ResetPasswordView.swift
Issue Number: 
- Password TextField Visible 아이콘 버그 수정
=> [Fix] Password TextField Visible 아이콘 버그 수정

hongmumuk_SwiftUI/Feature/Auth/SignupEmailFeature.swift, hongmumuk_SwiftUI/Feature/Auth/SignupEmailView.swift, hongmumuk_SwiftUI/Feature/Auth/VerifyEmailFeature.swift, hongmumuk_SwiftUI/Feature/Auth/VerifyEmailView.swift, hongmumuk_SwiftUI/Feature/Reusable/CommonTextFieldView.swift
Issue Number: 
- Verify Email, SignupEmail Feature에 이메일 재전송 타이머 추가
=> [Feat] Verify Email 타이머 추가 

hongmumuk_SwiftUI/Dependency/Client/LikeClient.swift, hongmumuk_SwiftUI/Dependency/Error/RestaurantListError.swift, hongmumuk_SwiftUI/Feature/Detail/DetailFeature.swift, hongmumuk_SwiftUI/Feature/Home/HomeRootView.swift, hongmumuk_SwiftUI/Feature/Like/LikeEmptyView.swift, hongmumuk_SwiftUI/Feature/Like/LikeFeature.swift, hongmumuk_SwiftUI/Feature/Like/LikeListView.swift, hongmumuk_SwiftUI/Feature/Like/LikeView.swift
=> [Refactor] like 기능 실제 API 연결

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Enums/ProfileSet.swift, hongmumuk_SwiftUI/Extension/Bundle+.swift, hongmumuk_SwiftUI/Feature/Auth/RootFeature.swift, hongmumuk_SwiftUI/Feature/Auth/RootView.swift, hongmumuk_SwiftUI/Feature/Category/CategoryListView.swift, hongmumuk_SwiftUI/Feature/Category/CategoryView.swift, hongmumuk_SwiftUI/Feature/Detail/DetailFeature.swift, hongmumuk_SwiftUI/Feature/Home/HomeView.swift, hongmumuk_SwiftUI/Feature/Like/LikeHeaderView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileFeature.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileHeaderView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInquryButton.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileSetListView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileSetView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileView.swift, hongmumuk_SwiftUI/Feature/Reusable/InquiryButton.swift, hongmumuk_SwiftUI/Feature/Reusable/WebContentView.swift, hongmumuk_SwiftUI/Feature/Reusable/WebView.swift, hongmumuk_SwiftUI/Feature/Reusable/WebViewHeader.swift
=> [Feat] profile 기능 초기 개발

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Assets.xcassets/verificationIcon.imageset/Contents.json, hongmumuk_SwiftUI/Assets.xcassets/verificationIcon.imageset/verificationIcon.svg, hongmumuk_SwiftUI/Dependency/Client/ProfileClient.swift, hongmumuk_SwiftUI/Dependency/Error/NickNameError.swift, hongmumuk_SwiftUI/Dependency/Error/ProfileError.swift, hongmumuk_SwiftUI/Dependency/Model/ProfileModel.swift, hongmumuk_SwiftUI/Enums/TextFieldState.swift, hongmumuk_SwiftUI/Feature/Auth/RootView.swift, hongmumuk_SwiftUI/Feature/Profile/InfoView.swift, hongmumuk_SwiftUI/Feature/Profile/PasswordView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInfoFeature.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInfoTapButtonView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInfoTapView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInfoView.swift, hongmumuk_SwiftUI/Feature/Reusable/WebViewHeader.swift, hongmumuk_SwiftUI/Utility/CommonTextfieldStyle.swift
=> [feat] 닉네임 변경 UI/ API 연동

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Dependency/Client/ProfileClient.swift, hongmumuk_SwiftUI/Dependency/Error/DeleteAccountError.swift, hongmumuk_SwiftUI/Dependency/Error/PostPasswordError.swift, hongmumuk_SwiftUI/Feature/Profile/InfoView.swift, hongmumuk_SwiftUI/Feature/Profile/PasswordView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInfoFeature.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInfoTapView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileInfoView.swift, hongmumuk_SwiftUI/Feature/Reusable/CommonTextFieldView.swift, hongmumuk_SwiftUI/Feature/Reusable/GrayPlainButton.swift, hongmumuk_SwiftUI/Utility/CommonTextfieldStyle.swift
=> [feat] 비밀번호 변경 기능 추가

hongmumuk_SwiftUI/Feature/Auth/FindPassword/ResetPasswordView.swift, hongmumuk_SwiftUI/Feature/Auth/FindPassword/VerifyEmailFeature.swift
Issue Number: 
- 안내문구 띄어쓰기 수정
- 기존 회원이 아닐 경우 에러 메시지
=> [Fix]  비밀번호 찾기 UI 수정

hongmumuk_SwiftUI/Feature/Detail/DetailInfoView.swift
Issue Number: 
- 식당 상세 키워드 패딩 추가 (잘리는 문제 해결)
=> [Fix] 식당 상세 키워드 패딩 추가 (잘리는 문제 해결)

hongmumuk_SwiftUI/Feature/Auth/Signup/PrivacyView.swift, hongmumuk_SwiftUI/Feature/Auth/Signup/SignupEmailView.swift, hongmumuk_SwiftUI/Feature/Auth/Signup/SignupPasswordView.swift
Issue Number: 
- 안내 문구 띄어쓰기 수정 "한번 더 " -> "한 번 더" 
- 기존 회원이 아닐 경우 에러 메시지 추가 "기존 회원이 아닙니다."
=> [Fix] 안내 문구 띄어쓰기 수정, 기존 회원이 아닐 경우 에러 메시지 추가

hongmumuk_SwiftUI/Enums/Epmty.swift, hongmumuk_SwiftUI/Feature/Auth/RootView.swift, hongmumuk_SwiftUI/Feature/Auth/Signup/PrivacyModalView.swift, hongmumuk_SwiftUI/Feature/Random/RandomFeature.swift, hongmumuk_SwiftUI/Feature/Random/RandomView.swift
- 문구 수정
- 랜덤에서 디테일 화면 진입 기능 추가
=> [refactor] 3차 QA

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Dependency/Client/APIClient.swift, hongmumuk_SwiftUI/Dependency/Client/AuthClient.swift, hongmumuk_SwiftUI/Dependency/Client/LikeClient.swift, hongmumuk_SwiftUI/Dependency/Client/ProfileClient.swift, hongmumuk_SwiftUI/Dependency/Client/RestaurantClient.swift, hongmumuk_SwiftUI/Feature/Auth/Onboarding/OnboardingView.swift, hongmumuk_SwiftUI/Feature/Auth/RootFeature.swift, hongmumuk_SwiftUI/Feature/Auth/RootView.swift, hongmumuk_SwiftUI/Utility/NetworkInterceptor.swift, hongmumuk_SwiftUI/Utility/Notification.swift
Issue Number: 
1. 토큰 재발급 로직 수정 
- 앱 진입점: 토큰 포맷으로 expired 여부 파악
- 앱 실행중: Interceptor 추가하여 에러코드 401일 경우 재발급 진행 
2. 앱 진입점 로직 수정 
- isLoading -> isFirstLaunch -> isLoggedin 순서로 상태 파악 진행 
- isLoading: 스플래쉬 화면 -> UX를 위해 1초 유지 
- onboarding: 시작하기 버튼 두개중 하나를 누르면 RootFeature의 onboardingCompleted 액션 활성화 -> isFirstLaunch 상태 반영 -> 홈 뷰로 변경 
- RootView가 .OnAppear될때마다 checkLoginStatus하는 로직 삭제 -> SplashView가 보여질때(앱 진입)만 check하도록 수정 -> 무한로딩 수정 
https://github.com/user-attachments/assets/8f93a89e-4968-48ad-99d9-5e12f32e75a1
=> [Refactor] 무한로딩 버그 수정, Token Interceptor 추가

hongmumuk_SwiftUI/Feature/Auth/Onboarding/OnboardingView.swift
Issue Number: 
- 홍무묵 시작하기 버튼 -> 로그인으로 뷰 수정 
- onboarding completed 액션 실행 시 자동으로 RootView Group 조건문의 else 실행 -> 로그인 뷰
=> [Refactor] Onboarding View - 홍무묵 시작하기 버튼 네비게이션 수정 

hongmumuk_SwiftUI/Assets.xcassets/Signup/arrowIcon.imageset/Contents.json, hongmumuk_SwiftUI/Enums/ProfileSet.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileFeature.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileSetListView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileSetView.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileView.swift, hongmumuk_SwiftUI/Localization/Script/en.lproj/Localizable.strings, hongmumuk_SwiftUI/Localization/Script/ko.lproj/Localizable.strings, hongmumuk_SwiftUI/Localization/Script/zh-Hans.lproj/Localizable.strings
=> [feat] 언어 설정 기능 추가

hongmumuk_SwiftUI/Feature/Auth/Signup/SignupEmailView.swift, hongmumuk_SwiftUI/Feature/Auth/Signup/SignupPasswordView.swift, hongmumuk_SwiftUI/Localization/Script/en.lproj/Localizable.strings, hongmumuk_SwiftUI/Localization/Script/ko.lproj/Localizable.strings, hongmumuk_SwiftUI/Localization/Script/zh-Hans.lproj/Localizable.strings
Issue Number: 
- Signup Email View: 인증코드 보내는 Text, 남은 시간 Text, 인증 코드 제목 Text 로컬라이제이션
- SignupPasswordView: 인증코드를 한번 더 입력하라는 안내 Text 로컬라이제이션
=> [fix] SignupEmailView, SignupPasswordView 로컬라이제이션

hongmumuk_SwiftUI.xcodeproj/project.pbxproj, hongmumuk_SwiftUI/Feature/Detail/DetailInfoView.swift
=> [hotfix] 상세 페이지 식당이름 국제화

hongmumuk_SwiftUI/Dependency/Client/RestaurantClient.swift, hongmumuk_SwiftUI/Feature/Detail/DetailFeature.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileFeature.swift, hongmumuk_SwiftUI/Feature/Profile/ProfileMyReviewsView.swift
Issue Number: 
- 리뷰 삭제 기능을 추가했습니다
=> [Feat] 리뷰 삭제 기능 추가

hongmumuk_SwiftUI/Extension/View+.swift, hongmumuk_SwiftUI/Feature/Detail/DetailFeature.swift, hongmumuk_SwiftUI/Feature/Detail/DetailTabView.swift, hongmumuk_SwiftUI/Feature/Reusable/OptimizedAsyncImage.swift, hongmumuk_SwiftUI/Feature/Reusable/ReviewItemView.swift
- QA 대응
- 이미지 해상도 변경
- 앱링크 버튼 레이아웃 수정
- 리뷰 디테일 화면에서 하단 탭바 제거
=> [Fix] 1.5차 QA 대응
